name: Build and Push Docker Image

on:
  push:
    branches:
      -development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout Repository
      uses: action/checkout@v2

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action @v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Docker Image
      uses: docker/buile-push-action@v2
      with:
        context: 
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/next-ci-cd:development